### ISSUE TITLE
Weird error issue makes handlers return null even if error is nil

### ISSUE THREAD

**Issue by s00500** [go-chai/chai#23]
Hey, awesome project!!!

I was just playing with it a bit and I could not make my get handler return data, I always got null. after digging a little around I found that errors.Is(err, nil) seems to always return false, and therefore always handles the response as if it would have been an error.... did you see this before ? I have tried with beta 1 and 2... the code I use matches the chi example very closely...

After playing with it for a bit more time I found that I could make it work by creating a new variable using the errortype first like so:

```
func (h *ResHandler[Res, Err]) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	res, code, err := h.f(w, r)
	var nilErr Err
	if !errors.Is(err, nilErr) {
```

It is generally still a little strange to me, as I do not understand why nil suddenly gets somehow linked to the type ?! Anyways, maybe you have some thoughts to this...

Greetings, Lukas

**Comment by e-nikolov** [comment]
Hi, thanks for checking out the project!

I'm trying to reproduce the issue, can you let me know which version of chai you are using and if this test passes for you:

https://github.com/go-chai/chai/blob/main/chai/chai_test.go#L69

```
go test ./chai/... -v
```

**Comment by e-nikolov** [comment]
I was able to reproduce the issue, it happens when the error is of a custom type, for which I was missing a test case.

And it happens because nils also have types and the types must also match in order for 2 nils to be considered equal.

https://go.dev/play/p/8lAPoouuSoV

Looking at the generics proposal and their [suggestion](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#the-zero-value) for handling zero values, your workaround is probably the way to go.

**Comment by s00500** [comment]
Hi @e-nikolov, 
I used the latest tag

github.com/go-chai/chai v0.12.0
github.com/go-chi/chi/v5 v5.0.7

If I directly checkout the repo at this tag (= master) then I can run the test, I did try that before writing this issue...

But I noticed that in the test you are using the default error, instead of a custom error type as done in the example... 

So to provide a more fitting testcase I added the custom errortype from the example and used in the testcase, and voila: it failed

```
type Error struct {
	Message          string `json:"error"`
	ErrorDebug       string `json:"error_debug,omitempty"`
	ErrorDescription string `json:"error_description,omitempty"`
	StatusCode       int    `json:"status_code,omitempty"`
}

func (e *Error) Error() string {
	return e.Message
}
```


```
		{
			name: "res handler",
			makeHandler: func(t *testing.T) http.Handler {
				return chai.NewResHandler(func(w http.ResponseWriter, r *http.Request) (*tests.TestResponse, int, *Error) {
					return newRes(), http.StatusOK, nil
				})
			},
			response: `{"foo":"f","bar":"b","test_inner_response":{"foo_foo":123,"bar_bar":12}}`,
		},
```

❯ go1.18beta1 test ./chai
--- FAIL: TestReqResHandler (0.00s)
    --- FAIL: TestReqResHandler/res_handler (0.00s)
        chai_test.go:106:
            	Error Trace:	chai_test.go:106
            	            				chai_test.go:99
            	Error:      	Not equal:
            	            	expected: map[string]interface {}(map[string]interface {}{"bar":"b", "foo":"f", "test_inner_response":map[string]interface {}{"bar_bar":12, "foo_foo":123}})
            	            	actual  : <nil>(<nil>)
            	Test:       	TestReqResHandler/res_handler
FAIL
FAIL	github.com/go-chai/chai/chai	0.324s
FAIL

**Comment by s00500** [comment]
Oh wow, sorry I just noticed that you wrote 2 messages, seems like we came to the same conclusion after all =D

**Comment by s00500** [comment]
And reading it now again I remember reading that part of the generics proposal myself, thinking it would be logical once I encounter it, did not think I would hit it so soon and in such a confusing way...

Spew is a cool tool, have not used it myself a lot yet, just the standard &+v and %#v, but these are not so obvious...
so to summarize: today I learned: nils are typed... =D

**Comment by e-nikolov** [comment]
There is a related gotcha with returning a custom error type that I've run into a couple of times: https://go.dev/play/p/-RhVHhZaPju

But I didn't realize it also happens here.

**Comment by e-nikolov** [comment]
Some more background info https://go.dev/doc/faq#nil_error

**Comment by s00500** [comment]
I assume this passage will become less relevant in code that uses generics for errortypes....

`
It's a good idea for functions that return errors always to use the error type in their signature (as we did above) rather than a concrete type such as *MyError, to help guarantee the error is created correctly. As an example, [os.Open](https://go.dev/pkg/os/#Open) returns an error even though, if not nil, it's always of concrete type [*os.PathError](https://go.dev/pkg/os/#PathError).
`

**Comment by e-nikolov** [comment]
Can you check if this PR https://github.com/go-chai/chai/pull/24 fixes the issue?

**Comment by s00500** [comment]
Nice, I can confirm that #24 closes this issue! I also tested responding with the custom error type from the handler, all fine, all as expected :-)

**Comment by e-nikolov** [comment]
Thanks for your assistance, let me know if you encounter any other issues.
